---
config:
    layout: elk
---
graph LR
    subgraph 0 ["(0) Module"]
        direction LR
        subgraph 1 ["(1) FuncDefn: #quot;main#quot;"]
            direction LR
            2["(2) Input"]
            3["(3) Output"]
            subgraph 4 ["(4) [**DFG**]"]
                direction LR
                style 4 stroke:#832561,stroke-width:3px
                5["(5) Input"]
                6["(6) Output"]
                7["(7) ieq"]
                8["(8) TestOp"]
                5--"0:0<br>int(5)"-->7
                5--"1:1<br>int(5)"-->7
                7--"0:0<br>Bool"-->8
                8--"0:0<br>Bool"-->6
            end
            2--"0:0<br>int(5)"-->4
            2--"1:1<br>int(5)"-->4
            4--"0:0<br>Bool"-->3
        end
    end
